import { Link } from "react-router-dom";
import styles from "../DashboardPage.module.css";
import { projectsList, templates } from "../dashboard.data";
import { MultiScreenRenderer, StylePresetPreview } from "../dashboard-preview";

export function DashboardSections({ onSelectTemplate }: { onSelectTemplate: (templateId: string) => void }) {
  return <>
    <section className={styles.projectsSection}><div className={styles.sectionHeader}><div><span className={styles.subHeader}>PROJELERİM</span><h2>Diğer projelerin</h2></div><Link to="/app/projeler" className={styles.linkMore}>Tümünü gör →</Link></div><div className={styles.projectGrid}>{projectsList.map((project) => <Link key={project.id} to={`/app/projeler/${project.id}/studio`} className={styles.projectCard}><div className={styles.projectCardPreviewHeader}><div className={styles.cardPreviewGlow} /><MultiScreenRenderer direction={project.direction} /></div><div className={styles.projectCardBody}><div className={styles.cardDirectionPill}>{project.direction}</div><div className={styles.cardTitleRow}><h3>{project.name}</h3><span className={styles.screenCountBadge}>{project.screens} ekran</span></div><p>{project.description}</p><div className={styles.cardFooterMeta}><span>{project.lastUpdated}</span><span className={styles.cardArrow}>Düzenle →</span></div></div></Link>)}</div></section>
    <section className={styles.inspirationSection}><div className={styles.sectionHeader}><div><span className={styles.subHeader}>İlham ve şablonlar</span><h2>Profesyonel tasarım sistemleri</h2><p>Aynı ürün içeriği, beş farklı görsel sistem. Şablon ürün alanını değil yalnızca tasarım dilini değiştirir.</p></div></div><div className={styles.templateGrid}>{templates.map((tpl) => <div key={tpl.id} className={styles.templateCard}><div className={styles.templatePreviewWindow} style={{ background: tpl.previewColor }}><StylePresetPreview presetId={tpl.id} /></div><div className={styles.templateMeta}><div className={styles.templateHeaderRow}><span className={styles.templateCategory}>{tpl.category}</span><span className={styles.templateDirectionTag}>{tpl.strategy.visualDirection}</span></div><h3>{tpl.name}</h3><p>{tpl.description}</p><p>{tpl.system.signatureComponents.slice(0, 2).join(" · ")}</p><div className={styles.templateFooterRow}><span className={styles.templateScreenTag}>v{tpl.version} · {tpl.strategy.cardStyle}</span><button className={styles.useStyleBtn} onClick={() => onSelectTemplate(tpl.id)}>Bu sistemi kullan</button></div></div></div>)}</div></section>
  </>;
}
